### ISSUE TITLE
Could color be disabled?

### ISSUE THREAD

**Issue by nbigaouette** [sebasmagri/env_logger#45]
I really like the new format, including the color!

Unfortunately when the log output is piped and stored elsewhere (for example in AWS CloudWatch) I see all the control characters which makes reading the log actually harder.

Could the color be disabled with a feature flag?

**Comment by KodrAus** [comment]
Hi @nbigaouette. I think this is a reasonable thing for us to do. Rather than a feature flag I think an environment variable might be a better fit here (since it's the environment that determines whether or not colours are going to be useful).

Like other `env_logger` settings, we can pick up this environment variable in the default builder, or let you read it yourself when configuring a logger. Maybe we can call the default environment variable `RUST_LOG_STYLE`. A value of `0` means no colour or styling. If there is no value, or it's not `0`, then we write colour and style. This is the opposite behaviour to the `RUST_BACKTRACE` environment variable.

What do you think?

**Comment by nbigaouette** [comment]
An environment variable makes absolute sense, specially for **env**_logger... ;)

The advantage of a feature flag would be to prevent having to pull some dependencies, which might speed up CI runs.

I feel like `RUST_LOG_STYLE` sounds more a way to control the style, not an on-off flag. But that's still what the 0 or 1 value mean, it applies a style to the logging (or not). There's not much else that it can do; either there is style, or there isn't.

In any way, the variable you suggested would definitely fit my use case! Thanks a lot! 👍

**Comment by kpcyrd** [comment]
I'd suggest to align this with cargo and others, so you would have `never`, `always` and `auto`, where `auto` means it tests if it's writing to [a tty][0] and disables colors if it isn't. This is usually good enough. If you run `./app` on your terminal you have colors, if you run `./app > log 2>&1` you don't. :)

[0]: http://lessis.me/atty/atty/index.html

**Comment by KodrAus** [comment]
Ah thanks @kpcyrd! I hadn't realised cargo had values for adjusting style output already. I was aligning this with `RUST_BACKTRACE`, but aligning with `--color` makes much more sense.
