### ISSUE TITLE
Allow disabling the humantime dependency

### ISSUE THREAD

**Issue by briansmith** [sebasmagri/env_logger#72]
Some environments, e.g. Kubernetes, already timestamp every log message. Thus, adding our own timestamp if wastefully duplicative. We currently have a custom formatter to disable the timestamping.

That works OK, as far as the runtime characteristic of the application are concerned. However, because Cargo downloads each dependency serially, and because Cargo builds each dependency serially, every single dependency inhibits the build performance by some constant factor that's independent of the complexity of the dependency. Some applications have continuous integration and/or container build systems that have to rebuild everything from scratch any time any dependency changes, and/or on every commit, so minimizing the from-scratch download + build time is important.

I noticed when upgrading such an application from env_logger 0.4 to env_logger 0.5 that chrono and then later humantime were added as dependencies. In our situation this is a regression, since it increases the number of dependencies (and thus the application size and the build time) compared to env_logger 0.4. We can't stay with env_logger 0.4 because some other libraries we use depend on env_logger 0.5 already; we're actually trying to optimize the build so that only only version of env_logger (0.5) needs to be built.

For these reasons, it would be beneficial to make the dependency on humantime, and the default timestamping functionality in general, optional, e.g. by making them configurable via a default feature, perhaps named "timestamp".

**Comment by KodrAus** [comment]
Related to #71

Thanks for the input @briansmith! I've been wondering about this, but haven't had a strong enough opinion either way to investigate it further.

It seems reasonable for `env_logger` to be built with `--no-default-features` and avoid pulling in dependencies you don't need if that's important to you. The switch from `chrono` to `humantime` should be an improvement in compile times and binary size. I'd rather frame these features as a way to avoid unnecessary dependencies, rather than a way to disable the timestamp in the default format or disable colour.

Perhaps we could have 2 features that control the dependencies we have now:

- `timestamp = ["humantime"]`
- `style = ["termcolor", "atty"]`

The `Formatter` abstraction _should_ encapsulate `termcolor` and `atty` enough to swap them out, besides the check to see if the buffer's style is equal to the thread-local one.

What do you think? Do you want to submit a PR for this?

**Comment by briansmith** [comment]
> The Formatter abstraction should encapsulate termcolor and atty enough to swap them out, besides the check to see if the buffer's style is equal to the thread-local one.

I see there is some `pub use` of types defined by these dependencies, e.g. `pub use termcolor::Color;` but I think that would be OK since everybody would have to opt into *not* having termcolor available by setting `default-features = false` in their `env_logger` dependency. Does that sound OK to you?

Otherwise we'd have to do env_logger 0.6, but I hope that's not necessary.

**Comment by BurntSushi** [comment]
> I see there is some pub use of types defined by these dependencies, e.g. pub use termcolor::Color;

Yikes. I do *not* think it is a good idea to have a public dependency on `termcolor`. If necessary, I need to be able to iterate on that crate by releasing semver bumps, and if it's a public dependency of a widely used crate, then that is not going to go over well. It also (I think) unnecessarily ties env_logger to a specific implementation of terminal colors.

If `Color` is the only such time then it should be straight-forward to create a wrapper type?

**Comment by KodrAus** [comment]
Yeh, `Color` is the only public part of `termcolor`'s API in `env_logger` so we could define our own equivalent `enum` and just completely decouple from `termcolor` publicly.

**Comment by KodrAus** [comment]
Ok, I've fixed up the issue using `termcolor` as a public dependency. It seemed worth getting this fixed for the majority of users sooner rather than later. Even though it's _theoretically_ a breaking change, I've decided it's better to just make it since a survey of public code and call for comments hasn't revealed anyone that would be affected, so will wear any potential flak from breaking the rules.
